name: CD - Deploy FastAPI App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3


      - name: Setup SSH Key and Known Hosts
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > aws-key.pem
          chmod 600 aws-key.pem
          mkdir -p ~/.ssh  # Ensure SSH directory exists
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts
        

      - name: Deploy to AWS EC2
        run: |
          ssh -i aws-key.pem ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} << 'EOF'
          cd /home/ubuntu/HNG_12_Stage_2_Backend  # Change this if needed
          git pull origin main
          source /home/ubuntu/ENV/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart fastapi
          sudo systemctl restart nginx
          EOF
